### ISSUE TITLE
Insterting Lines and Auto Renumber

### ISSUE THREAD

**Issue by amcguire07** [blandfbt/PPCL#13]
I am using Sublime with your PPCL package.  I am on a mac and having a hard time getting the insert and renumber to work.  I see that it is possible from the .gif but cannot figure out the commands to do it.  Any help you can provide would be appreciated.

**Comment by semiamaurotic** [comment]
There may be a couple of different issues...

1. How long ago did you install the package? Within the last few weeks a bug was patched that prevented the renumbering keyboard shortcut from triggering on mac. Try checking for updates through Package Control.

2. Whereas for most keyboard shortcuts in cross platform apps the `Ctrl` key on Windows becomes the `⌘ [command]` key on mac, the shortcuts in this package use the mac `^ [control]` key. So, the shortcut for renumbering is `^ + ⇧ + L` (`control + shift + L`), not `⌘ + ⇧ + L` (`command + shift + L`). 

Also, the package has been updated recently, so now entering the renumbering shortcut without selecting any text will renumber all lines, otherwise renumbering only applies to selected lines. You may also need to try reselecting your line increment (the one for when you hit return to add a new line) in <em><strong>Tools>PPCL>Line Increment Amount</strong></em>. (For some reason it doesn't show a checkmark next to the selected item, so just reselect your preferred increment. I think it defaults to 1.)

Please let me know if this resolves your issue.

**Comment by amcguire07** [comment]
I just downloaded and installed the package today and it states there are no updates.  I have tried to accomplish this with both the Ctrl and Command key and neither works.

**Comment by semiamaurotic** [comment]
Are you pretty familiar with Sublime Text 3 in general, or you new to it?

**Comment by amcguire07** [comment]
I am new to it.  It easily is something I am doing wrong but I cant seem to figure it out.  The gif shows it working exactly how I want it to but I can't replicate the steps.

**Comment by blandfbt** [comment]
The cool thing about Package Control is that it should check for updates for all installed packages whenever sublime text is restarted. So you will be up to date. 

For the functionality, do you not see a prompt at the bottom of the ST window when you press the keys? It should have a "None:None" prompt, where the first None is the starting line number you want, and the next None is increment amount. 

If you don't see that box, try navigating to the python console to see if there is an error message. That might give us more information. Keyboard shortcuts for the console in the link below

Docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_OS X.html#general

**Comment by semiamaurotic** [comment]
@amcguire07 No problem, I just want to make sure I don't gloss over any key details.
In the bottom right hand corner of the window does it show "PPCL" as the selected syntax?
<img width="1585" alt="selected syntax" src="https://cloud.githubusercontent.com/assets/13118282/23718291/ea60f168-0404-11e7-8e2d-a4d65812ab4a.png">

**Comment by amcguire07** [comment]
Yes I am in the PPCL syntax but I do not know what the python console is.  I have a window open at the bottom with the following messages:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "LineChanger in /Users/amcguire/Library/Application Support/Sublime Text 3/Installed Packages/PPCL Language Syntax and Editor.sublime-package", line 409, in run
ValueError: invalid literal for int() with base 10: ''

**Comment by semiamaurotic** [comment]
That is the console. (If you dismiss it, you can get it back by by going to <em><strong>View>Show Console</strong></em>)

Can you paste your code and/or a screenshot here?

**Comment by amcguire07** [comment]
<img width="844" alt="screen shot 2017-03-08 at 11 01 43 am" src="https://cloud.githubusercontent.com/assets/26280853/23719067/b226223e-03ee-11e7-9aa5-c8c2c22ee086.png">

**Comment by amcguire07** [comment]
I tried to reload the Package Control which accounts for the new messages in the console.

**Comment by semiamaurotic** [comment]
I think you've uncovered a bug. 
Try putting a comment or some code on the final line after the line number.

**Comment by amcguire07** [comment]
It let me add the Comment but the add line still didn't work. 
<img width="843" alt="screen shot 2017-03-08 at 11 15 20 am" src="https://cloud.githubusercontent.com/assets/26280853/23719506/8e2feebc-03f0-11e7-9ad1-ba061aa1aad1.png">

**Comment by semiamaurotic** [comment]
Oh, I see. Try manually changing the last line number to something like 30000, then put the cursor on the line above and hit return.
I think this will work until the bug can be fixed.

**Comment by amcguire07** [comment]
I can add at the end no problem but I want to be able to insert if I have to amend the code after I've already written it. I am newer to this type of code so I know I will be making a lot of correction and insertions.

Sent from my iPhone

On Mar 8, 2017, at 2:23 PM, Nathan Watkins <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, I see. Try manually changing the last line number to something like 30000, then put the cursor on the line above and hit return.
I think this will work until the bug can be fixed.

**Comment by blandfbt** [comment]
Definitely. We will dive into it. I don't have a mac with me right now, but will when I get home. 

Are you new to PPCL? If so, welcome! We are working on making this editor even easier for people who are new to the language, so sick with it and it will be great. 

Brien Blandford

**Comment by amcguire07** [comment]
I appreciate the help!

I am new to PPCL.  I have many years with ALC and now I am trying to wrap new.

**Comment by semiamaurotic** [comment]
@blandfbt I'm seeing the same behavior in Sublime Text 3 on Windows. I think the issue is there are blank lines after the final numbered line.

@amcguire07 Try using your mouse or arrow keys to move the cursor to the bottom of the file and delete any blank lines following the last numbered line, then see whether you can add new line by hitting return.

**Comment by amcguire07** [comment]
I can add lines at the end but not in the middle.

**Comment by semiamaurotic** [comment]
@blandfbt The version I get through Package Control, with a clean install today, doesn't have the popup warnings and some other recent changes. Do you have to add a new version tag for Package control to serve up our recent changes?

**Comment by blandfbt** [comment]
Quite possibly.  I will add that tonight, and make some edits to the readme
file and help commands.

**Comment by blandfbt** [comment]
Tag updated to v1.9.0  so you should all get pushed the new changes through Package Control.  I'll look into the issue amcguire07 mentioned, and see if that push fixed it.

**Comment by blandfbt** [comment]
Before
![before](https://cloud.githubusercontent.com/assets/10290469/23737436/e7a2e11e-0447-11e7-9f65-190bb02f8df3.png)


After
![after](https://cloud.githubusercontent.com/assets/10290469/23737441/f238e22c-0447-11e7-8992-0a6b3dd35411.png)


So, I was working off a git pull, not package control.  And I update the tag to v1.9.0
However, Package Control is still on v1.8.0.  I'll have to find out why that is.  I don't know if there is a frequency they check for updates, and we just have to wait for that window??? Every time I have pushed a new tag in the past, it fetched it on package control.  I would assume it rasters through their json list of packages over some interval, and the updates them.  So hang tight, @amcguire07 , it should come through shortly.  If it doesn't, I'll ping package control.

for now, you can press ctrl+` and enter the console.  then type <view.run_command("call_adjust")> without the brackets and it will run the line changer command directly instead of the key mapping.

**Comment by amcguire07** [comment]
Thank you for the help!!!!

**Comment by blandfbt** [comment]
Package updated to v1.9.0. Let me know if you are able to use the key mapping now. 

Brien Blandford

**Comment by amcguire07** [comment]
I can get the renumbering to work with the console command but it still doesn't appear to be working with the keymapping.

**Comment by semiamaurotic** [comment]
@blandfbt I'm getting an error on upgrade, and when trying a clean install. The console shows:
`Package Control: Error downloading package. HTTP error 500 downloading https://codeload.github.com/blandfbt/PPCL/zip/v1.9.0.
error: Package Control
Unable to download PPCL Language Syntax and Editor. Please view the console for more details.`

@amcguire07 I suspect your package may not have updated successfully either. You can check your PPCL package version number by opening Package Control (command + shift + P) --> "Package Control: List Packages" --> PPCL (the description in this list view should show the version number). Does yours show v1.8.0 or v1.9.0?

**Comment by amcguire07** [comment]
@semiamaurotic You are correct, I still have v1.8.0

I had the same error downloading and followed the manual process but it must not have updated correctly.

**Comment by blandfbt** [comment]
So, there is some issue with package control.  I'll try to dig into that.
Sorry for the problems.

**Comment by semiamaurotic** [comment]
In the meantime, if you unzip this file, and put it in your **//Users/[username]/Library/Application Support/Sublime Text 3/Packages/User** folder, it will fix the keybinding issue.

[Default (OSX).sublime-keymap.zip](https://github.com/blandfbt/PPCL/files/831909/Default.OSX.sublime-keymap.zip)

**Comment by blandfbt** [comment]
That will work, but I need to fix the package control.  I doubt that key
mapping will change significantly, but if we add new features and new key
maps, a manual file input may override others, in the similar fashion as
the MRO for a child class in python.  So, just be aware, once the package
updates automatically, I would remove the manual file.

**Comment by amcguire07** [comment]
@blandfbt @semiamaurotic  Thank your so much for your help with this!

**Comment by blandfbt** [comment]
Happy coding!  and thanks @semiamaurotic

**Comment by blandfbt** [comment]
@amcguire07 Just wondering if the package worked because the new version downloaded, or because you dropped the file @semiamaurotic sent you into the package directory?  On my mac, I have v1.9.0 (hit shift+command+p to bring up the prompt, type "package control: list packages" and see what comes up.).  Did yours download to the newest version?  It seems to be working with the key mapping for me now, and I am wondering if it's working for you.

**Comment by amcguire07** [comment]
I am using the dropped file.  My package is still on 1.8 and there are no updates when I check.

**Comment by semiamaurotic** [comment]
You might want to try removing the package and reinstalling it from Package Control. I just tried it on my other machine, and it successfully installed version 1.9.1.

**Comment by amcguire07** [comment]
I deleted and reinstalled and that put me on 1.9.1

**Comment by blandfbt** [comment]
Great.  It should update automatically from now on.  I have no idea what
the hang up was.  Thanks @semiamaurotic for the fix.
